/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boxcount;

import static boxcount.BoxCount.colorLimits;
import java.util.Arrays;
import javax.swing.JTextField;

/**
 *
 * @author Simon
 */
public class ColorConfig extends javax.swing.JDialog {

    JTextField[] arrEdits;
    
    /**
     * Creates new form ColorConfig
     */
    public ColorConfig(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    void setup(){
        arrEdits = new JTextField[8];
        arrEdits[0] = edtWhite;
        arrEdits[1] = edtBlue;
        arrEdits[2] = edtCyan;
        arrEdits[3] = edtGreen;
        arrEdits[4] = edtYellow;
        arrEdits[5] = edtOrange;
        arrEdits[6] = edtRed;
        arrEdits[7] = edtMagenta;
        btnResetActionPerformed(null);
        btnReset.setToolTipText(Arrays.toString(colorLimits));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlExplanation = new javax.swing.JScrollPane();
        edtExplanation = new javax.swing.JTextPane();
        lblWhite = new javax.swing.JLabel();
        edtWhite = new javax.swing.JTextField();
        edtBlue = new javax.swing.JTextField();
        edtCyan = new javax.swing.JTextField();
        edtGreen = new javax.swing.JTextField();
        edtYellow = new javax.swing.JTextField();
        edtOrange = new javax.swing.JTextField();
        edtRed = new javax.swing.JTextField();
        edtMagenta = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnAbort = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblBlue = new javax.swing.JLabel();
        lblCyan = new javax.swing.JLabel();
        lblGreen = new javax.swing.JLabel();
        lblYellow = new javax.swing.JLabel();
        lblOrange = new javax.swing.JLabel();
        lblRed = new javax.swing.JLabel();
        lblMagenta = new javax.swing.JLabel();
        lblPink = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Farben konfigurieren");

        pnlExplanation.setEnabled(false);

        edtExplanation.setEditable(false);
        edtExplanation.setText("Werte müssen zwischen 1 & 2 liegen sowie mindestens gleich dem vorherigen sein!");
        edtExplanation.setEnabled(false);
        pnlExplanation.setViewportView(edtExplanation);

        lblWhite.setText("Weiß, wenn <");

        edtWhite.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        edtWhite.setText("Weiß");

        edtBlue.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        edtBlue.setText("Blau");

        edtCyan.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        edtCyan.setText("Cyan");

        edtGreen.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        edtGreen.setText("Grün");

        edtYellow.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        edtYellow.setText("Gelb");

        edtOrange.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        edtOrange.setText("Orange");

        edtRed.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        edtRed.setText("Rot");

        edtMagenta.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        edtMagenta.setText("Magenta");

        btnOK.setText("OK");
        btnOK.setPreferredSize(new java.awt.Dimension(114, 25));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnAbort.setText("Abbrechen");
        btnAbort.setPreferredSize(new java.awt.Dimension(114, 25));
        btnAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbortActionPerformed(evt);
            }
        });

        btnReset.setText("Zurücksetzen");
        btnReset.setPreferredSize(new java.awt.Dimension(114, 25));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblBlue.setText("Blau, wenn <");

        lblCyan.setText("Cyan, wenn <");

        lblGreen.setText("Grün, wenn <");

        lblYellow.setText("Gelb, wenn <");

        lblOrange.setText("Orange, wenn <");

        lblRed.setText("Rot, wenn <");

        lblMagenta.setText("Magenta, wenn <");

        lblPink.setText("sonst Pink");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPink)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlExplanation, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWhite)
                                    .addComponent(lblBlue)
                                    .addComponent(lblCyan)
                                    .addComponent(lblGreen)
                                    .addComponent(lblYellow)
                                    .addComponent(lblOrange)
                                    .addComponent(lblRed)
                                    .addComponent(lblMagenta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(edtRed, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtOrange, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtYellow, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtGreen, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtCyan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtBlue, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtWhite)
                                    .addComponent(edtMagenta)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAbort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlExplanation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWhite)
                    .addComponent(edtWhite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBlue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtCyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCyan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGreen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtYellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYellow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtMagenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMagenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        for (int i = 0; i < arrEdits.length; i++){
            arrEdits[i].setText(Double.toString(colorLimits[i]));
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbortActionPerformed
        btnResetActionPerformed(evt);
        setVisible(false);
    }//GEN-LAST:event_btnAbortActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (BCUtil.checkColorLimits(this, arrEdits)){
            for (int i = 0; i < arrEdits.length; i++){
                colorLimits[i] = Double.parseDouble(arrEdits[i].getText());
            }
            setVisible(false);
        }
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ColorConfig dialog = new ColorConfig(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbort;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField edtBlue;
    private javax.swing.JTextField edtCyan;
    private javax.swing.JTextPane edtExplanation;
    private javax.swing.JTextField edtGreen;
    private javax.swing.JTextField edtMagenta;
    private javax.swing.JTextField edtOrange;
    private javax.swing.JTextField edtRed;
    private javax.swing.JTextField edtWhite;
    private javax.swing.JTextField edtYellow;
    private javax.swing.JLabel lblBlue;
    private javax.swing.JLabel lblCyan;
    private javax.swing.JLabel lblGreen;
    private javax.swing.JLabel lblMagenta;
    private javax.swing.JLabel lblOrange;
    private javax.swing.JLabel lblPink;
    private javax.swing.JLabel lblRed;
    private javax.swing.JLabel lblWhite;
    private javax.swing.JLabel lblYellow;
    private javax.swing.JScrollPane pnlExplanation;
    // End of variables declaration//GEN-END:variables
}
